app/Modules/Project/routes/web.php
<?php

Route::group([
    'prefix' => 'admin',
    'middleware' => [ 'web', 'language'],
    'namespace' => 'App\Modules\Project\Http\Controllers'], function () {

    Route::group(['middleware' => 'guardAuth:admin'], function() {
        Route::resource('project','BackendController');
        Route::delete('project/{id}/remove-images/{image_id}', 'BackendController@removeImages');
    });
});

Route::group([
    'middleware' => [ 'web', 'localeSessionRedirect', 'localizationRedirect', 'localeViewPath'],
    'prefix'    =>  \Mcamara\LaravelLocalization\Facades\LaravelLocalization::setLocale(),
    'namespace' => 'App\Modules\Project\Http\Controllers'], function () {
    Route::group([
        'prefix' => 'projects',
    ], function () {
        Route::get('/','FrontendController@index')->name('projects.index');
        Route::get('/{project}', 'FrontendController@show')->name('projects.show');
    });



});

app/Modules/Project/Models/Project.php
<?php
/**
 * Created by PhpStorm.
 * User: dosar
 * Date: 01.10.2018
 * Time: 18:18
 */

namespace App\Modules\Project\Models;


use App\Modules\Image\Models\Image;
use Dosarkz\Dosmin\Models\I18nModel;

class Project extends I18nModel
{
    const STATUS_DISABLE = 0;
    const STATUS_ACTIVE = 1;
    const TYPE_COMPLEX = 1;
    const TYPE_INDUSTRIAL = 2;

    protected $fillable = [
        'title_ru', 'title_en', 'title_kz', 'image_id', 'description_ru', 'description_en', 'description_kz', 'city_ru',
        'city_en', 'city_kz', 'year_ru', 'year_en', 'year_kz', 'sum_of_area_ru', 'sum_of_area_en', 'sum_of_area_kz',
        'additions_ru', 'additions_en', 'additions_kz', 'floor_ru', 'floor_en', 'floor_kz', 'status_id', 'type_id'
    ];

    public $timestamps = true;

    public function getStatusesAttribute()
    {
        return [
            self::STATUS_ACTIVE => 'Активен',
            self::STATUS_DISABLE => 'Не активен'
        ];
    }

    public function listStatuses()
    {
        return [
            self::STATUS_ACTIVE => 'Активен',
            self::STATUS_DISABLE => 'Не активен'
        ];
    }

    public function getStatusAttribute()
    {
        return $this->listStatuses()[$this->status_id] ?? null;
    }

    public function image()
    {
        return $this->belongsTo(Image::class,'image_id');
    }

    public function images()
    {
        return $this->hasMany(ProjectImage::class, 'project_id')->with('image')
            ->orderByDesc('created_at');
    }

    public function getTypeListAttribute()
    {
        return [
            self::TYPE_COMPLEX          => 'Жилые комплексы',
            self::TYPE_INDUSTRIAL       => 'Промышленный сектор',
        ];
    }

    public function getTypeAttribute()
    {
        return $this->typeList[$this->type_id];
    }


}

app/Modules/Project/Models/ProjectImage.php
<?php
/**
 * Created by PhpStorm.
 * User: dosar
 * Date: 01.10.2018
 * Time: 18:21
 */

namespace App\Modules\Project\Models;


use App\Modules\Image\Models\Image;
use Illuminate\Database\Eloquent\Model;

class ProjectImage extends Model
{
    const STATUS_ACTIVE = 1;

    protected $fillable = [
        'image_id', 'project_id'
    ];

    public $timestamps = true;

    public function image()
    {
        return $this->belongsTo(Image::class, 'image_id');
    }
}

app/Modules/Project/Http/Controllers/BackendController.php
<?php

namespace App\Modules\Project\Http\Controllers;

use App\Modules\Image\Models\Image;
use App\Modules\Project\Models\Project;
use App\Modules\Project\Models\ProjectImage;
use Dosarkz\Dosmin\Controllers\CrudController;
use Dosarkz\LaravelUploader\BaseUploader;
use Illuminate\Http\Request;

class BackendController extends CrudController
{
    protected $storeValidationRules = [
        'title_ru' => 'required',
        'description_ru'  => 'required',
        'status_id' =>  'required',
        'type_id'   =>  'required'
    ];

    public $afterSaveRedirectUrl = '/admin/project';

    public function __construct()
    {
        $this->setModel(new Project());
        $this->setViewPath('project::backend');
        $this->setFormUrl('admin/project');
        $this->setModule('project');
    }

    protected function beforeValidate(Request $request)
    {
    }

    protected function beforeSave(&$data, $model)
    {
        if (request()->hasFile('image'))
        {
            $file = BaseUploader::image(request()->file('image'),'uploads/news',true, 1024, 768,
                null, 330);

            $image = Image::create([
                'name' => $file->getFileName(),
                'thumb' => $file->getThumb(),
                'path' => $file->getDestination()
            ]);

            $data['image_id'] = $image->id;
        }
    }

    protected function afterSave($model)
    {
        if (request()->hasFile('images')) {
            foreach (request()->file('images') as $item) {
                $uploader = BaseUploader::image($item, 'uploads/projects');
                $image = Image::create([
                    'name' => $uploader->getFileName(),
                    'thumb' => $uploader->getThumb(),
                    'path' => $uploader->getDestination()
                ]);

                ProjectImage::create([
                    'image_id' => $image->id,
                    'project_id' => $model->id,
                    'status_id' => ProjectImage::STATUS_ACTIVE,
                ]);
            }
        }
    }

    public function show($alias)
    {
        $model = $this->getModel()->where('url', $alias)->first();

        if(!$model)
        {
            abort(404);
        }

        $this->setShowParams([
            'model' => $model,
            'url' => $this->getFormUrl(),
            'viewPath' => $this->getViewPath()
        ]);
        return view(sprintf('%s.show', $this->getViewPath()),$this->getShowParams());
    }

    /**
     * @param $page_id
     * @return \Illuminate\Http\RedirectResponse
     */
    public function removeImage($page_id)
    {
        $article = Project::findOrFail($page_id);

        if(!$article->image_id)
        {
            return redirect()->back();
        }

        $image = Image::findOrFail($article->image_id);

        if(file_exists(public_path($image->getThumb())))
        {
            unlink(public_path($image->getThumb()));
        }
        if(file_exists(public_path($image->getFullImage())))
        {
            unlink(public_path($image->getFullImage()));
        }

        $image->delete();

        $article->image_id = Null;
        $article->save();

        return redirect()->back()->with('success', trans('admin::base.photo_deleted'));
    }

    /**
     * @param $imageId
     * @return \Illuminate\Http\RedirectResponse
     */
    public function removeImages($project_id, $imageId)
    {
        $projectImage = ProjectImage::findOrFail($imageId);

        if ($projectImage) {
            if (file_exists(public_path($projectImage->image->getThumb()))) {
                unlink(public_path($projectImage->image->getThumb()));
            }

            if (file_exists(public_path($projectImage->image->getFullImage()))) {
                unlink(public_path($projectImage->image->getFullImage()));
            }

            $projectImage->image->delete();
            $projectImage->delete();
        }

        return redirect()->back()->with('success', 'Фото успешно удалено');
    }
}

app/Modules/Project/Http/Controllers/FrontendController.php
<?php

namespace App\Modules\Project\Http\Controllers;

use App\Modules\Project\Models\Project;
use Dosarkz\Dosmin\Controllers\ModuleController;

class FrontendController extends ModuleController
{
    public function index()
    {
        $models = Project::whereStatusId(Project::STATUS_ACTIVE)->get();
        $complexes = Project::where('type_id', Project::TYPE_COMPLEX)->get();
        $industrials =  Project::where('type_id', Project::TYPE_INDUSTRIAL)->get();

        return view('project::frontend.index', compact('complexes', 'industrials', 'models'));
    }

    public function show(Project $project)
    {
        return view('project::frontend.show', compact('project'));
    }
}

app/Modules/Project/Resources/views/backend/create.blade.php
@extends('admin::layouts.app')
@section('content')
    <div class="box box-body">
        <div class="box-header with-border">
            <h3 class="box-title">{{trans('admin::base.add')}} проект</h3>
        </div>

        @include("{$viewPath}.form")
    </div>
@endsection

@section('css')
    <link rel="stylesheet" href="/vendor/admin/datepicker/datepicker3.css">
@endsection

@section('js')
    <script src="/vendor/admin/ckeditor/ckeditor.js"></script>
@endsection
@section('js-append')
    <script>
        CKEDITOR.replace('description_ru');
        CKEDITOR.replace('description_en');
        CKEDITOR.replace('description_kz');
    </script>
@endsection

app/Modules/Project/Resources/views/backend/edit.blade.php
@extends('admin::layouts.app')
@section('content')
    <div class="box box-body">
        <div class="box-header with-border">
            <h3 class="box-title">{{trans('admin::base.edit')}} {{ucfirst($module->name)}}</h3>
        </div>

        @include("{$viewPath}.form")
        @include('admin::modals.remove_image_modal')
    </div>
@endsection
@section('css')
    <link rel="stylesheet" href="/vendor/admin/datepicker/datepicker3.css">
@endsection

@section('js')
    <script src="/vendor/admin/ckeditor/ckeditor.js"></script>
@endsection
@section('js-append')
    <script>
        $(document).ready(function() {

            $('#remove-image').on('show.bs.modal', function (event) {
                var button = $(event.relatedTarget);
                var action = button.data('action');
                var modal = $(this);

                modal.find('#removeImageForm').attr('action', action)
            })
        });

        CKEDITOR.replace('description_ru');
        CKEDITOR.replace('description_en');
        CKEDITOR.replace('description_kz');
    </script>
@endsection

app/Modules/Project/Resources/views/backend/form.blade.php
<div class="container">
    <div class="row">
        <div class="col-md-8">
            <div class="box-body">

        @if (count($errors) > 0)
            <div class="alert alert-danger">
                <ul>
                    @foreach ($errors->all() as $error)
                        <li>{{ $error }}</li>
                    @endforeach
                </ul>
            </div>
        @endif

        @if($model->exists)
            {{ Form::open(array('url' => sprintf('/%s/%s',$url, $model->id),'method'=> 'PUT', 'name'=>'update-article', 'files' => true))}}
        @else
            {{ Form::open(array('url' => sprintf('/%s',$url),'method'=> 'POST', 'name'=>'create-article', 'files' => true))}}
        @endif


        <!-- Nav tabs -->
            <ul class="nav nav-tabs" role="tablist">
                <li role="presentation" class="active"><a href="#ru" aria-controls="ru" role="tab"
                                                          data-toggle="tab">На русском</a></li>
                <li role="presentation"><a href="#en" aria-controls="en" role="tab" data-toggle="tab">На
                        английском</a></li>

                <li role="presentation"><a href="#kz" aria-controls="kz" role="tab" data-toggle="tab">На
                        казахском</a></li>
            </ul>

            <!-- Tab panes -->
            <div class="tab-content">
                <div role="tabpanel" class="tab-pane active" id="ru">
                    @include('project::backend.form_ru', compact('model','categories'))
                </div>
                <div role="tabpanel" class="tab-pane" id="en">
                    @include('project::backend.form_en', compact('model','categories'))
                </div>

                <div role="tabpanel" class="tab-pane" id="kz">
                    @include('project::backend.form_kz', compact('model','categories'))
                </div>

                <div class="form-group">
                    <label class="control-label" for="type">Тип</label>
                    {{Form::select('type_id', $model->typeList, $model->type_id, ['class' => 'form-control', 'placeholder' =>
                    'Выберите'])}}
                </div>


                <div class="form-group">
                    <label class="control-label" for="preview">Фото</label>
                    <input type="file" id="image" name="image">

                    @if($model->image)
                        <img src="/{{$model->image->getThumb()}}" alt=""/>
                    @endif

                </div>

                <div class="form-group">
                    <label class="control-label" for="images">Фотографии</label>
                    <input type="file" id="images" name="images[]" multiple="multiple">
                </div>

                @if($model->images)
                    @foreach($model->images as $image)
                        <div class="form-group">
                            <img width="200" src="/{{$image->image->getThumb()}}" alt="" class="thumbnail"/>

                            <button type="button" class="btn btn-warning remove-news-image"
                                    data-action="/admin/project/{{$model->id}}/remove-images/{{$image->id}}"
                                    data-toggle="modal" data-target="#remove-image">
                                <span  class="glyphicon glyphicon-remove"></span> удалить
                            </button>
                        </div>
                    @endforeach
                @endif


                <div class="form-group">
                    <label class="control-label" for="title">{{trans('admin::base.status')}}</label>
                    {{Form::select('status_id', $model->statuses,$model->status_id,
                    ['class'   => 'form-control' ,'placeholder' =>  trans('admin::base.choose')])}}
                </div>
            </div>


            @if($model->exists)
                {{ Form::submit('Обновить', ['class' => 'btn btn-primary']) }}
            @else
                {{ Form::submit('Создать',  ['class' => 'btn btn-primary']) }}
            @endif
            {{ Form::close() }}

            <div>
            </div>
            </div>
        </div>
    </div>

app/Modules/Project/Resources/views/backend/form_en.blade.php
<div class="box-body">
    <div class="form-group">
        <label class="control-label" for="title">Название</label>
        {{Form::text('title_en',$model->title_en, ['class' => 'form-control']) }}
    </div>

    <div class="form-group">
        <label class="control-label" for="desc">Описание</label>
        {{Form::textarea('description_en',$model->description_en, ['class' => 'form-control',
        'id' => 'description_en', 'cols' => 30, 'rows' => 30
        ]) }}
    </div>

    <div class="form-group">
        <label class="control-label" for="city_param">Город</label>
        {{Form::text('city_en', $model->city_en, ['class' => 'form-control', 'placeholder' => 'Город'])}}
    </div>

    <div class="form-group">
        <label class="control-label" for="city_param">Год</label>
        {{Form::text('year_en', $model->year_en, ['class' => 'form-control', 'placeholder' => 'Год'])}}
    </div>

    <div class="form-group">
        <label class="control-label" for="city_param">Общая площадь</label>
        {{Form::text('sum_of_area_en', $model->sum_of_area_en, ['class' => 'form-control', 'placeholder' => 'Общая площадь'])}}
    </div>

    <div class="form-group">
        <label class="control-label" for="city_param">Составляющие</label>
        {{Form::text('additions_en', $model->additions_en, ['class' => 'form-control', 'placeholder' => 'Состовляющие'])}}
    </div>

    <div class="form-group">
        <label class="control-label" for="city_param">Этажность</label>
        {{Form::text('floor_en', $model->floor_en, ['class' => 'form-control', 'placeholder' => 'Этажность'])}}
    </div>


</div>

app/Modules/Project/Resources/views/backend/form_kz.blade.php
<div class="box-body">
    <div class="form-group">
        <label class="control-label" for="title">Название</label>
        {{Form::text('title_kz',$model->title_kz, ['class' => 'form-control']) }}
    </div>

    <div class="form-group">
        <label class="control-label" for="desc">Описание</label>
        {{Form::textarea('description_kz',$model->description_kz, ['class' => 'form-control',
        'id' => 'description_kz', 'cols' => 30, 'rows' => 30
        ]) }}
    </div>

    <div class="form-group">
        <label class="control-label" for="city_param">Город</label>
        {{Form::text('city_kz', $model->city_kz, ['class' => 'form-control', 'placeholder' => 'Город'])}}
    </div>

    <div class="form-group">
        <label class="control-label" for="city_param">Год</label>
        {{Form::text('year_kz', $model->year_kz, ['class' => 'form-control', 'placeholder' => 'Год'])}}
    </div>

    <div class="form-group">
        <label class="control-label" for="city_param">Общая площадь</label>
        {{Form::text('sum_of_area_kz', $model->sum_of_area_kz, ['class' => 'form-control', 'placeholder' => 'Общая площадь'])}}
    </div>

    <div class="form-group">
        <label class="control-label" for="city_param">Составляющие</label>
        {{Form::text('additions_kz', $model->additions_kz, ['class' => 'form-control', 'placeholder' => 'Состовляющие'])}}
    </div>

    <div class="form-group">
        <label class="control-label" for="city_param">Этажность</label>
        {{Form::text('floor_kz', $model->floor_kz, ['class' => 'form-control', 'placeholder' => 'Этажность'])}}
    </div>


</div>

app/Modules/Project/Resources/views/backend/form_ru.blade.php
<div class="box-body">
    <div class="form-group">
        <label class="control-label" for="title">Название</label>
        {{Form::text('title_ru',$model->title_ru, ['class' => 'form-control']) }}
    </div>


    <div class="form-group">
        <label class="control-label" for="desc">Описание</label>
        {{Form::textarea('description_ru',$model->description_ru, ['class' => 'form-control',
        'id' => 'description_ru', 'cols' => 30, 'rows' => 30
        ]) }}
    </div>


    <div class="form-group">
        <label class="control-label" for="city_param">Город</label>
        {{Form::text('city_ru', $model->city_ru, ['class' => 'form-control', 'placeholder' => 'Город'])}}
    </div>

    <div class="form-group">
        <label class="control-label" for="city_param">Год</label>
        {{Form::text('year_ru', $model->year_ru, ['class' => 'form-control', 'placeholder' => 'Год'])}}
    </div>

    <div class="form-group">
        <label class="control-label" for="city_param">Общая площадь</label>
        {{Form::text('sum_of_area_ru', $model->sum_of_area_ru, ['class' => 'form-control', 'placeholder' => 'Общая площадь'])}}
    </div>

    <div class="form-group">
        <label class="control-label" for="city_param">Составляющие</label>
        {{Form::text('additions_ru', $model->additions_ru, ['class' => 'form-control', 'placeholder' => 'Состовляющие'])}}
    </div>

    <div class="form-group">
        <label class="control-label" for="city_param">Этажность</label>
        {{Form::text('floor_ru', $model->floor_ru, ['class' => 'form-control', 'placeholder' => 'Этажность'])}}
    </div>


</div>

app/Modules/Project/Resources/views/backend/index.blade.php
@extends('admin::layouts.app')

@section('content')
    <div class="box box-primary">
        <div class="box-header with-border">
            <h3 class="box-title">{{trans('admin::base.list')}} проектов</h3>
        </div>
        @include('admin::modals.modal')
        <div class="row">
            <div class="col-md-12">
                <table class="table">
                    <thead class="thead-inverse">
                    <tr>
                        <th>{{trans('admin::base.id')}}</th>
                        <th>{{trans('admin::base.title')}}</th>
                        <th>Тип</th>
                        <th>{{trans('admin::base.status')}}</th>
                        <th>{{trans('admin::base.actions')}}</th>
                    </tr>
                    </thead>
                    <tbody>
                    @foreach($models as $model)
                        <tr>
                            <td>{{ $model->id }}</td>
                            <td>{{ $model->title }}</td>
                            <td>{{$model->type}}</td>
                            <td>{{ $model->status }}</td>
                            <td>
                                <a class="btn btn-xs btn-primary" href="/{{$url}}/{{ $model->id }}/edit"><i class="fa fa-pencil" aria-hidden="true"></i></a>
                                {{ Form::open(array('url' => '/'.$url.'/' . $model->id, 'class' => 'form-delete', 'style' => 'display:inline;')) }}
                                {{ Form::hidden('_method', 'DELETE') }}
                                <button class="btn btn-xs btn-danger delete" type="submit"><i class="fa fa-times" aria-hidden="true"></i></button>
                                {{ Form::close() }}
                            </td>
                        </tr>
                    @endforeach
                    </tbody>
                </table>
                {{ $models->links() }}
            </div>
        </div>
    </div>
@endsection

app/Modules/Project/Resources/views/backend/show.blade.php
@extends('admin::layouts.app')

@section('content')
    <div class="box box-primary">
        <div class="box-header with-border">
            <h3 class="box-title">{{trans('admin::base.preview')}}</h3>
        </div>

        <div class="box-body">
            <table class="table table-bordered">
                <tr>
                    <td>{{trans('admin::base.title')}}:</td>
                    <td>{{$model->title}}</td>
                </tr>

                <tr>
                    <td>{{trans('admin::base.photo')}}:</td>
                    <td><img src="{{url($model->image ? $model->image->getThumb() : "")}}" alt=""></td>
                </tr>

                <tr>
                    <td>{{trans('admin::base.date')}}:</td>
                    <td>{!!$model->created_at !!}</td>
                </tr>

                <tr>
                    <td>{{trans('admin::base.short_description')}}:</td>
                    <td>{!!  $model->short_description!!}</td>
                </tr>

                <tr>
                    <td>{{trans('admin::base.description')}}:</td>
                    <td>{!!$model->description !!}</td>
                </tr>
            </table>
        </div>
    </div>
@endsection

app/Modules/Project/Resources/views/frontend/index.blade.php
@extends('layouts.app')
@section('title', trans('app.objects.title'))
@section('content')
    <div class="conntainer-fluid">
        @include('layouts.partials.header')
    </div>
    <div class="container mar-bot">
        <div class="row">
            <div class="col-md-12 text-center">
                <p class="main-block__title">{{trans('app.objects.title')}}</p>
            </div>
        </div>
        <div class="container">
            <div class="row">
                <div class="col-md-12 col-sm-12 col-12">
                    <ul class="nav nav-pills mb-3 custom-navs" id="pills-tab" role="tablist">
                        <li class="nav-item">
                            <a class="nav-link active" id="pills-home-tab" data-toggle="pill" href="#pills-home" role="tab" aria-controls="pills-home" aria-selected="true">{{trans('app.objects.title')}}</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" id="pills-profile-tab" data-toggle="pill" href="#pills-profile" role="tab" aria-controls="pills-profile" aria-selected="false">
                                <img src="/img/icons/build.png" alt="">
                                {{trans('app.objects.cat_1')}}
                            </a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" id="pills-contact-tab" data-toggle="pill" href="#pills-contact" role="tab" aria-controls="pills-contact" aria-selected="false">
                                <img src="/img/icons/factory.png" alt="">
                                {{trans('app.objects.cat_2')}}
                            </a>
                        </li>
                    </ul>

                    <div class="tab-content" id="pills-tabContent">
                        <div class="tab-pane fade show active" id="pills-home" role="tabpanel" aria-labelledby="pills-home-tab">
                            <div class="container">
                                <div class="row">
                                    <div class="projects-info__row col-md-12 col-sm-12 col-12">

                                        <div class="stat-block">
                                            <p class="stat-block__number">{{$models->count()}}</p>
                                            <p class="stat-block__text">{{trans('app.objects.desc')}}</p>
                                        </div>

                                       @foreach($models as $complex)
                                            <div class="projects-info">
                                                @if($complex->image)
                                                    <img class="projects-info__image" src="{{url($complex->image->getThumb())}}" alt="">
                                                @endif
                                                <div class="projects-info__text-wrap">
                                                    <p class="projects-info__title">{{$complex->title}}</p>
                                                    <p class="projects-info__date">Сдан: {{$complex->year}}</p>
                                                    <div class="projects-info__action-wrap">
                                                        <a href="{{route('projects.show', $complex->id)}}" class="projects-info__action">{{trans('app.detail')}}
                                                            <img src="/img/icons/left-arrow.svg" alt="">
                                                        </a>
                                                    </div>
                                                </div>
                                            </div>
                                           @endforeach
                                    </div>
                                </div>
                            </div>
                        </div>

                        <div class="tab-pane fade" id="pills-profile" role="tabpanel" aria-labelledby="pills-profile-tab">
                            <div class="container">
                                <div class="row">
                                    <div class="projects-info__row col-md-12 col-sm-12 col-12">

                                    @foreach($complexes as $complex)
                                        <div class="projects-info">
                                            @if($complex->image)
                                                <img class="projects-info__image" src="{{url($complex->image->getThumb())}}" alt="">
                                            @endif
                                            <div class="projects-info__text-wrap">
                                                <p class="projects-info__title">{{$complex->title}}</p>
                                                <p class="projects-info__date">Сдан: {{$complex->year}}</p>
                                                <div class="projects-info__action-wrap">
                                                    <a href="{{route('projects.show', $complex->id)}}" class="projects-info__action">{{trans('app.detail')}}
                                                        <img src="/img/icons/left-arrow.svg" alt="">
                                                    </a>
                                                </div>
                                            </div>
                                        </div>
                                    @endforeach
                                </div>
                                </div>
                            </div>
                        </div>

                        <div class="tab-pane fade" id="pills-contact" role="tabpanel" aria-labelledby="pills-contact-tab">
                            <div class="container">
                                <div class="row">
                                    <div class="projects-info__row col-md-12 col-sm-12 col-12">
                                    @foreach($industrials as $industrial)
                                        <div class="projects-info">
                                            @if($industrial->image)
                                                <img class="projects-info__image" src="{{url($industrial->image->getThumb())}}" alt="">
                                            @endif
                                            <div class="projects-info__text-wrap">
                                                <p class="projects-info__title">{{$industrial->title}}</p>
                                                <p class="projects-info__date">Сдан: {{$industrial->year}}</p>
                                                <div class="projects-info__action-wrap">
                                                    <a href="{{route('projects.show', $industrial->id)}}" class="projects-info__action">{{trans('app.detail')}}
                                                        <img src="/img/icons/left-arrow.svg" alt="">
                                                    </a>
                                                </div>
                                            </div>
                                        </div>
                                    @endforeach
                                </div>
                                </div>
                            </div>
                        </div>

                    </div>
                </div>




            </div>



        </div>

    </div>
    <div class="container-fluid footer-container">
        @include('layouts.partials.footer')
    </div>
@endsection