app/Modules/Menu/routes/web.php
<?php

Route::group([
    'prefix' => 'admin',
    'middleware' => [ 'web', 'language'],
    'namespace' => 'App\Modules\Menu\Http\Controllers'], function () {

    Route::group(['middleware' => ['guardAuth:admin', 'role:admin']], function() {
        Route::resource('menu','MenuController');
        Route::resource('menu.items', 'MenuItemController');
    });
});

app/Modules/Menu/Models/Menu.php
<?php

namespace App\Modules\Menu\Models;

use App\Modules\Role\Models\Role;
use Dosarkz\Dosmin\Models\I18nModel;
use Dosarkz\Dosmin\Models\Module;

class Menu extends I18nModel
{
    const TYPE_LEFT_SIDE_MENU = 1;
    const STATUS_ACTIVE = 1;
    const STATUS_DISABLE = 0;
    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name_ru', 'name_en','alias', 'type_id', 'module_id', 'status_id', 'user_id', 'position'
    ];

    public $timestamps = true;


    public function getTypesAttribute()
    {
        return [self::TYPE_LEFT_SIDE_MENU => trans('admin::base.left_menu')];
    }

    public function getModulesAttribute()
    {
        return Module::pluck('name_'.app()->getLocale(),'id');
    }

    public function getStatusAttribute()
    {
        return $this->statuses[$this->status_id];
    }

    public function getStatusesAttribute()
    {
        return [
            self::STATUS_DISABLE => trans('admin::base.deactivate'),
            self::STATUS_ACTIVE => trans('admin::base.active')
        ];
    }
    public function menuItems()
    {
        return $this->hasMany(MenuItem::class, 'menu_id');
    }

    public function menuParentItems()
    {
        return $this->hasMany(MenuItem::class, 'menu_id')->whereNull('parent_id');
    }

    public function scopeVisible($query)
    {
        return $query->whereHas('menuRoles', function($dubQuery){
            $dubQuery->whereHas('superUserRoles',function($userQuery){
                $userQuery->where('super_user_id', auth()->guard('admin')->user()->id);
            });
        });
    }

    public function module()
    {
        return $this->belongsTo(Module::class, 'module_id');
    }

    public function menuRoles()
    {
        return $this->hasMany(MenuRole::class, 'menu_id');
    }

    public function menuRole($role_id)
    {
        return MenuRole::where('role_id', $role_id)->where('menu_id', $this->id)->first();
    }

}

app/Modules/Menu/Resources/views/create.blade.php
@extends('admin::layouts.app')
@section('title')
    {{trans('admin::base.add')}} {{ucfirst($module->name)}}
@endsection
@section('content')
    <div class="box box-primary">
        <div class="box-header with-border">
            <h3 class="box-title">{{trans('admin::base.create')}} {{ucfirst($module->name)}}</h3>
        </div>
        <div class="box-body">
            @include($module->alias.'::form',compact('model'))
        </div>

    </div>

@endsection

app/Modules/Menu/Resources/views/edit.blade.php
@extends('admin::layouts.app')
@section('content')
    <div class="box box-primary">
        <div class="box-header with-border">
            <h3 class="box-title">{{trans('admin::base.edit')}} {{ucfirst($module->name)}}</h3>
        </div>
        <div class="box-body">
            @include($module->alias.'::form',compact('model'))
        </div>
    </div>
@endsection

app/Modules/Menu/Resources/views/form.blade.php
@if($model->exists)
    {{ Form::open(array('url' => '/admin/'.$module->alias.'/'.$model->id,'method'=> 'PUT', 'name'=>'update-superUser', 'files' => true))}}
@else
    {{ Form::open(array('url' => '/admin/'.$module->alias,'method'=> 'POST', 'name'=>'post-superUser','files' => true))}}
@endif

@if (count($errors) > 0)
    <div class="alert alert-danger">
        <ul>
            @foreach ($errors->all() as $error)
                <li>{{ $error }}</li>
            @endforeach
        </ul>
    </div>
@endif


<ul class="nav nav-tabs" role="tablist">
    <li role="presentation" class="active"><a href="#en" aria-controls="en" role="tab" data-toggle="tab">{{trans('admin::base.in_english')}}</a></li>
    <li role="presentation"><a href="#ru" aria-controls="ru" role="tab" data-toggle="tab">{{trans('admin::base.in_russian')}}</a></li>
</ul>


<div class="tab-content">

    <div role="tabpanel" class="tab-pane  active" id="en">
        <br>
        <div class="form-group{{ $errors->has('name_en') ? ' has-error' : '' }}">
            <div class="row">
                <label for="name" class="col-md-4 control-label">{{trans('admin::base.name')}}</label>

                <div class="col-md-6">
                    {{Form::text('name_en', $model->name_en, ['class' => 'form-control', 'placeholder' => trans('admin::base.title')])}}

                    @if ($errors->has('name_en'))
                        <span class="help-block">
                                        <strong>{{ $errors->first('name_en') }}</strong>
                                    </span>
                    @endif
                </div>
            </div>
        </div>

        <div class="form-group{{ $errors->has('type_id') ? ' has-error' : '' }}">
            <div class="row">
                <label for="name" class="col-md-4 control-label">{{trans('admin::base.type')}}</label>

                <div class="col-md-6">
                    {{Form::select('type_id', $model->types, $model->type_id, ['class' => 'form-control',
                     'placeholder' => trans('admin::base.choose')])}}

                    @if ($errors->has('type_id'))
                        <span class="help-block">
                                        <strong>{{ $errors->first('type_id') }}</strong>
                                    </span>
                    @endif
                </div>
            </div>
        </div>


        <div class="form-group{{ $errors->has('module_id') ? ' has-error' : '' }}">
            <div class="row">
                <label for="name" class="col-md-4 control-label">{{trans('admin::base.module')}}</label>

                <div class="col-md-6">
                    {{Form::select('module_id', $model->modules, $model->module_id, ['class' => 'form-control',
                     'placeholder' => trans('admin::base.choose')])}}

                    @if ($errors->has('type_id'))
                        <span class="help-block">
                                        <strong>{{ $errors->first('type_id') }}</strong>
                                    </span>
                    @endif
                </div>
            </div>
        </div>

        <div class="form-group{{ $errors->has('position') ? ' has-error' : '' }}">
            <div class="row">
                <label for="icon" class="col-md-4 control-label">{{trans('admin::base.position')}}</label>

                <div class="col-md-6">
                    {{Form::number('position', $model->position, ['class' => 'form-control', 'placeholder' =>
                    trans('admin::base.position')])}}

                    @if ($errors->has('position'))
                        <span class="help-block">
                                        <strong>{{ $errors->first('position') }}</strong>
                                    </span>
                    @endif
                </div>
            </div>
        </div>


        <div class="form-group{{ $errors->has('status_id') ? ' has-error' : '' }}">
            <div class="row">
                <label for="name" class="col-md-4 control-label">{{trans('admin::base.status')}}</label>

                <div class="col-md-6">
                    {{Form::select('status_id', $model->statuses, $model->status_id, ['class' => 'form-control',
                     'placeholder' => trans('admin::base.status')])}}

                    @if ($errors->has('status_id'))
                        <span class="help-block">
                                        <strong>{{ $errors->first('status_id') }}</strong>
                                    </span>
                    @endif
                </div>
            </div>
        </div>


        <h3>{{trans('admin::base.visible')}}</h3>

        @foreach($roles as $role)
            <div class="form-group">
                <div class="row">
                    <label for="role-{{$role->alias}}" class="col-md-4 control-label">{{$role->name}}</label>
                    <div class="col-md-6">
                        @if(\App\Modules\Menu\Models\MenuRole::where('menu_id', $model->id)
                        ->where('role_id', $role->id)->first())
                            {{Form::checkbox('menuRole['.$role->id.']', true, true, ['id' => 'role-'.$role->alias])}}
                        @else
                            {{Form::checkbox('menuRole['.$role->id.']', false, false, ['id' => 'role-'.$role->alias])}}
                        @endif

                    </div>
                </div>
            </div>
         @endforeach




    </div>

    <div role="tabpanel" class="tab-pane" id="ru">
        <br>
        <div class="form-group{{ $errors->has('name_ru') ? ' has-error' : '' }}">
            <div class="row">
                <label for="name_ru" class="col-md-4 control-label">{{trans('admin::base.name')}}</label>

                <div class="col-md-6">
                    {{Form::text('name_ru', $model->name_ru, ['class' => 'form-control', 'placeholder' => trans('admin::base.title')])}}

                    @if ($errors->has('name_ru'))
                        <span class="help-block">
                                        <strong>{{ $errors->first('name_ru') }}</strong>
                                    </span>
                    @endif
                </div>
            </div>
        </div>
    </div>

    <br>
    @if($model->exists)
        {{ Form::submit(trans('admin::base.update'), ['class' => 'btn btn-primary']) }}
    @else
        {{ Form::submit(trans('admin::base.create'), ['class' => 'btn btn-primary']) }}
    @endif

    <a class="btn btn-info" href="{{url()->previous()}}">{{trans('admin::base.back')}}</a>

</div>

{{ Form::close() }}

app/Modules/Menu/Resources/views/index.blade.php
@extends('admin::layouts.app')

@section('content')

    <div class="nav-tabs-custom">
        <ul class="nav nav-tabs">
            <li class="active"><a href="#tab_1" data-toggle="tab" aria-expanded="true">{{trans('admin::base.menu')}}</a></li>
            <li class="pull-right"><a href="/admin/modules/{{$module->alias}}/settings" class="text-muted"><i class="fa fa-gear"></i></a></li>
        </ul>
        <div class="tab-content">
            <div class="tab-pane active" id="tab_1">


                <div class="container">
                    <div class="row">
                        <div class="col-md-10">
                            <div class="form-group">
                                <a class="btn btn-primary" href="/admin/{{$module->alias}}/create">{{trans('admin::base.create')}}</a>
                            </div>
                            <table class="table">
                                <thead class="thead-inverse">
                                <tr>
                                    <th>{{trans('admin::base.id')}}</th>
                                    <th>{{trans('admin::base.name')}}</th>
                                    <th>{{trans('admin::base.items')}}</th>
                                    <th>{{trans('admin::base.status')}}</th>
                                    <th>{{trans('admin::base.actions')}}</th>
                                </tr>
                                </thead>
                                <tbody>
                                @if(isset($model))
                                    @foreach($model as $item)
                                        <tr>
                                            <td>{{$item->id}}</td>
                                            <td>{{ $item->name }}</td>
                                            <td><a href="/admin/{{$module->alias}}/{{$item->id}}/items">{{$item->menuItems->count()}}</a></td>
                                            <td>{{ $item->status }}</td>
                                            <td>
                                                <a class="btn btn-xs btn-primary"  href="/admin/{{$module->alias}}/{{$item->id}}/edit"><i class="fa fa-pencil" aria-hidden="true"></i></a>
                                                {{ Form::open(array('url' => '/admin/'.$module->alias.'/' . $item->id, 'style' => 'display:inline;')) }}
                                                {{ Form::hidden('_method', 'DELETE') }}
                                                <button class="btn btn-xs btn-danger delete" data-target="#confirm"
                                                        data-toggle="modal" data-action="/admin/{{$module->alias}}/{{$item->id}}"
                                                        type="button"><i class="fa fa-times" aria-hidden="true"></i></button>
                                                {{ Form::close() }}
                                            </td>

                                        </tr>

                                    @endforeach
                                @endif


                                </tbody>
                            </table>

                        </div>

                        <div class="col-md-10">
                            <div class="form-group">
                                {{ $model->links() }}
                            </div>
                        </div>

                    </div>
                </div>
            </div>
        </div>
        <!-- /.tab-content -->
    </div>

    @include('admin::modals.base_modal')
@endsection

@section('js-append')

    <script>

        $('form.form-delete').on('click', function(e){
            e.preventDefault();
            var $form=$(this);
            $('#confirm').modal({ backdrop: 'static', keyboard: false })
                    .on('click', '#delete-btn', function(){
                        $form.submit();
                    });
        });

        $('#confirm').on('show.bs.modal', function (event) {
            var button = $(event.relatedTarget);
            var modal = $(this);

            modal.find('#removeForm').attr('action', button.data('action'))
        })
    </script>
    @endsection